### ISSUE TITLE
SSL error received, but what does it mean?

### ISSUE THREAD

**Issue by bnlawrence** [cedadev/MyProxyClient#10]
Starting from scratch:

``` python
import getpass
from myproxy.client import MyProxyClient
hostname='slcs1.ceda.ac.uk'
username='lawrence'
pwd = getpass.getpass()
c = MyProxyClient(hostname=hostname, caCertDir='./')
creds = c.logon(username, pwd, updateTrustRoots=True)
```
returns
```
Error: [('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')]
```
How should I interpret this?

**Comment by philipkershaw** [comment]
When the client gets the server certificate `ssl3_get_server_certificate`, it can't verify it: `certificate verify failed`.  I would check that you have any CA certificates in `./`.  If not, it means you need to run `logon` with `bootstrap` keyword: https://github.com/cedadev/MyProxyClient/blob/master/myproxy/client.py#L1406

To ensure that you have all the CA certificates you need to trust services in the federation (including the MyProxyCA at CEDA)

**Comment by bnlawrence** [comment]
Thanks. Probably a good idea to provide a more "user friendly error" ... with advice along the lines you've just provided :-) ... which worked!

**Comment by philipkershaw** [comment]
Glad it's fixed.  The root of the problem is that the OpenSSL library doesn't provide specific fine-grained exceptions types.  From memory, you only get `SSLError` returned.  This means that it's hard to provide more specific error info.   You could imagine a dictionary linking user-friendly errors to those obscure ones bubbled up from the OpenSSL libraries but this would be quite a bit of work and a cludge.
